#!/usr/bin/env python
from __future__ import print_function

import argparse
import datetime
import logging
import sys

from obspy import UTCDateTime

from sqlalchemy import engine_from_config
from sqlalchemy.orm import sessionmaker

from aqms_ir.configure import configure
from aqms_ir.inv2schema import _remove_station

# Global scope: start the engine and bind a Session factory to it
    
# create configured engine instance
global engine 
engine = engine_from_config(configure(), prefix='sqlalchemy.')

# create a configured "Session" class
Session = sessionmaker(bind=engine)

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Closes a station's       \
        active epochs to today's date unless otherwise requested with      \
        the -e flag. \
        Updates (PostgreSQL) AQMS tables station_data, channel_data,       \
        simple_response, channelmap_ampparms, channelmap_codaparms, and    \
        poles_and_zeros related tables. It does not remove any entries     \
        from the various dictionary tables.                                \
                                                                           \
        When a channel, or channel wildcard, is provided via the -c flag,  \
        only those channels will be closed.                                \
        The rest of the active channels will remain, and the station epoch \
        will remain open as well.            \
                                                                           \
        If an end-time is provided, the active channels will be ended on   \
        that date instead of the current date.                             \
                                                                           \
        Database connection parameters have to be set with environment     \
        variables DB_NAME, DB_HOST, DB_PORT, DB_USER, and optionally,      \
        DB_PASSWORD. \
                                                             \
        Logs are written to closeStation_YYYY-mm-ddTHH:MM:SS.log \
        See https://github.com/pnsn/aqms_ir") 

    # required argument
    help_text = "FDSN Network code, e.g. UW, CI, HV"
    parser.add_argument("network_code",help=help_text)
    help_text = "Station lookup code, e.g. ASR, PAS, LON, COR"
    parser.add_argument("station_code",help=help_text)

    # optional argument
    help_text = "Be more verbose in logfile"
    parser.add_argument("-v","--verbose",help=help_text,action="store_true")
    help_text = "Specify a channel code to close, wildcards are allowed"
    parser.add_argument("-c","--channel",help=help_text)
    help_text = "Specify an endtime in format YYYY/MM/dd"
    parser.add_argument("-e","--endtime",help=help_text)

    args = parser.parse_args()

    logfile = "closeStation_{}.log".format(datetime.datetime.now().strftime('%Y-%m-%dT%H:%M:%S'))
    logging.basicConfig(filename=logfile, level=logging.WARNING)
    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    logging.getLogger('sqlalchemy.engine').setLevel(logging.WARNING)
    
    logging.info("Closing meta-data for station {}.{}".format(args.network_code,args.station_code))
    print("Closing meta-data for station {}.{}".format(args.network_code,args.station_code))

    if args.channel_code:
        channel_code = args.channel_code
    else:
        channel_code = None
    session = Session()
    status = _close_station(session, args.network_code, args.station_code, channel=channel_code)
    session.close()

    logging.info("\nClosed {} station(s)".format(status))
    print("\nClosed {} station(s)".format(status))
    
    sys.exit(status)

